export enum textApp {
  address = 'Адресс маршрута:',
  nickname = 'Мое имя',
  saveWay = 'Сохранить путь',
  waySaved = 'Путь добавлен в историю',
  shared = 'Поделиться',
  sharedTitle = 'Тут текст',
  saveRoute = 'Сохраненные маршруты:',
  pause = 'Пауза',
  startTrekking = 'Запустить трекинг',
  emptyCoordinates = 'Координаты не могут быть пустыми',
  successfullyExported = 'Успешно экспротировано!',
  errorExported = 'Ошибка экспрота!',
  successImport = 'Успешно импортировано!',
  errorImport = 'Ошибка импорта!',
  exportedRouter = 'Экспортировать маршрут',
  friends = 'Друзья',
  history = 'История',
  profile = 'Профиль',
  sendRoute = 'Отправить свой маршрут',
  pickRoute = 'Выберите маршрут',
}
